name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      ls6_global_00:
        description: 'LS6 Global - 00'
        type: boolean
        default: false
      ls6_global_01:
        description: 'LS6 Global - 01'
        type: boolean
        default: false
      prod_global_00:
        description: 'Production Global - 00'
        type: boolean
        default: false
      prod_global_01:
        description: 'Production Global - 01'
        type: boolean
        default: false

jobs:
  create-environment-matrix:
    runs-on: windows-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Build Environment Matrix
        id: set-matrix
        shell: pwsh
        run: |
          $environments = @()
          $envMap = @{
            "ls6_global_00" = "LS6 Global - 00"
            "ls6_global_01" = "LS6 Global - 01"
            "prod_global_00" = "Production Global - 00"
            "prod_global_01" = "Production Global - 01"
          }
          foreach ($key in $envMap.Keys) {
              $envVariableName = $key.ToUpper()
              $inputValue = (Get-Item -Path "Env:\$envVariableName").Value
              if ($inputValue -eq 'true') {
                  $environments += $envMap[$key]
              }
          }
          if ($environments.Count -eq 0) {
              Write-Output "No environments selected. Exiting gracefully."
              $matrixJson = "{}"
          } elseif ($environments.Count -eq 1) {
              $matrixJson = @{ "include" = @(@{ "environment" = $environments[0] }) } | ConvertTo-Json -Depth 2 -Compress
          } else {
              $matrixJson = @{ "include" = $environments | ForEach-Object { @{ "environment" = $_ } } } | ConvertTo-Json -Depth 2 -Compress
          }
          Write-Output "matrix=$matrixJson" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Debug Generated Matrix
        run: 'echo "Generated Matrix: ${{ steps.set-matrix.outputs.matrix }}"'

  deploy:
    needs: create-environment-matrix
    strategy:
      matrix: ${{ fromJson(needs.create-environment-matrix.outputs.matrix) }}
      max-parallel: 1
      fail-fast: false
    runs-on: windows-latest
    environment: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PowerShell-YAML Module
        shell: pwsh
        run: Install-Module -Name powershell-yaml -Force -Scope CurrentUser

      - name: Generate Environment-Specific Config
        shell: pwsh
        run: ./generate-config.ps1 -environment "${{ matrix.environment }}"

      - name: Run PowerShell Script 1
        shell: pwsh
        run: |
          . .\config.ps1
          ./script1.ps1

  call-reusable-workflow:
    needs: deploy
    strategy:
      matrix: ${{ fromJson(needs.create-environment-matrix.outputs.matrix) }}
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      environment: ${{ matrix.environment }}
    name: Call Reusable Workflow for ${{ matrix.environment }}

  final-steps:
    needs: call-reusable-workflow
    runs-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.create-environment-matrix.outputs.matrix) }}
    steps:
      - name: Run PowerShell Script 2
        shell: pwsh
        run: |
          . .\config.ps1
          ./script2.ps1
